# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: two8g
email: ybxnice@gmail.com
description: 易斌鑫的学习博客
keywords: two8g 易斌鑫 编程技术 博客
favicon: /images/two8g_16x16.ico
url: "http://two8g.com" # the base hostname & protocol for your site
twitter_username: two8g
github_username:  two8g
oscgit_username: ybxgit
timezone: Asia/Shanghai

# Build settings
markdown: kramdown

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-71835017-1